# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
  pull_request:
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env: 
          POSTGRES_DB: apartment_scout_db 
          POSTGRES_USER: admin 
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
              # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: 'latest' # See https://hub.docker.com/_/postgres for available versions
          postgresql db: 'apartment_scout_db'
          postgresql user: 'admin'
          postgresql password: 'admin'
          postgresql init scripts: './db_init_scripts/'
    - run: npm test
